### ISSUE TITLE
kgdb cannot be connected, what is the situation

### ISSUE THREAD

**Issue by whiteHat001** [weltling/convey#1]
![image](https://user-images.githubusercontent.com/18191034/123571781-8bf94900-d7fd-11eb-8801-bc159f39277b.png)

**Comment by weltling** [comment]
Thanks for the report. I don't seem to see enough info to understand the issue. Could you expand on that please?

Thanks

**Comment by whiteHat001** [comment]
Thanks for your reply, I mean that according to your method, I can use kdb to debug the linux kernel, but my gdb cannot debug the kernel

**Comment by whiteHat001** [comment]
> Thanks for the report. I don't seem to see enough info to understand the issue. Could you expand on that please?
> 
> Thanks
Thanks for your reply, I mean that according to your method, I can use kdb to debug the linux kernel, but my gdb cannot debug the kernel

**Comment by whiteHat001** [comment]
> Thanks for the report. I don't seem to see enough info to understand the issue. Could you expand on that please?
> 
> Thanks

Thanks for your reply, I mean that according to your method, I can use kdb to debug the linux kernel, but my gdb cannot debug the kernel

**Comment by weltling** [comment]
Yeah, we need to go into detail. Unfortunately the screenshot doesn't show enough info to conclude what might have gone wrong. There can be many reasons why things can go wrong. For example, i don't really describe how to enable KGDB in kernel, but kernel needs to have the support loaded/built-in. It would rock if you could describe in detail what you did, so it could be reproduced and investigated further.

Please keep in mind also, that in some situations the order in which things are done matters. Perhaps you could also check several things before:

- Please verify the basic function of the named pipe is in place.
- Add `--poll` argument to the `convey` invocation.
- Add `kgdboc=` to the cmdline thus avoiding need to triggering the interrupt.

There might be something else, whereby I wouldn't expect things to have changed that much there would be some incompatibility.

Thanks

**Comment by whiteHat001** [comment]
Thanks!I suggest you to be more detailed here.

**Comment by weltling** [comment]
@whiteHat001 yeah, a readme can be extended. On your side, it would be helpful to hear what the steps was exactly, the current report is too sparse to start with.

thanks
